Layout/LineLength:
  Max: 150
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/MethodLength:
  Max: 30
  Exclude:
    - test/*
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Exclude:
    - test/*

Style/StderrPuts:
  Enabled: false 
Style/PercentLiteralDelimiters:
  Enabled: false  
Style/Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false


AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'share/ruby/vendor/**/*'
    - test/*
