Style/StringLiterals:
  Enabled: false 
Layout/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 200
Style/StderrPuts:
  Enabled: false 
Style/PercentLiteralDelimiters:
  Enabled: false  
Style/Documentation
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
  
AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - "share/ruby/vendor/**/*"
