name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Bats
      run: |
        git clone https://github.com/sstephenson/bats
        sudo ./bats/install.sh /usr/local
    - name: Run tests
      run: |
        bats --help
